# Generated by Django 4.0.5 on 2022-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemart',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/items'),
            preserve_default=False,
        ),
    ]
